= Staff systems
:Author:    Alexis Luengas
:Email:     <alexis.luengas@gmail.com>
:toc:
:toc-placement!:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

toc::[]

== Overview

Cavatina is a language for creating musical notation and a font system
that renders it. It focuses on ease of input and portability and is
primarly suited for music teaching and quick drafting of ideas.
Portability is achieved in a very unique manner. Cavatina sheet music
_is_ text and as such it will support all common text manipulation
commands. As you write, the input is interpreted straight away by the
text engine, so that firstly it won't feel like coding and, more
importantly, there is no need to “compile” it. This makes Cavatina
really portable. It is ideal for traveling and teaching music. Also, it
can be easily embedded as a webfont in any website.

The font implements a rendering concept which could be called
_image-as-text_, using implicit compilation of a text engine via
contextual character substitutions. This has the advantage of supporting
all common text manipulation functions of any rich text editor, such as
copy, paste, cut, and undo. As a plain font, Cavatina can be embedded
into a web page or web app with minimal effort.

[NOTE]
Cavatina renders on the latest versions of Chrome, Firefox and Opera.

== Language overview

You type in your music _sequentially_, i.e. the same way as in written
language. Chords are words, bar-lines are punctuation marks, accidentals
are diacritics and staff lines are the space character. Here is the base
of Cavatina’s syntax:

1.  Hitting space extends the staff for starting a new note/chord.
2.  Notes within a chord are typed in _from low to high_.
3.  Note modifiers are written directly _after_ the corresponding note.

== Character mapping

Notes and all other musical symbols are accessed directly with your
computer keyboard. The input depends on what keyboard layout you use.
The complete keyboard mapping for each layout can be found on the
http://cavatinafont.com/en/keyboard[keyboard page]. If you are new to
Cavatina, it is a better idea to read through the short documentation
first.

== The musical note

The location of each note is motivated by the fact that the lowest row
of characters just above the space bar has exactly *seven letters*: the
seven pitches of a diatonic scale.

It is easy to learn where this seven notes are because their physical
location on the keyboard.

Most musicians aren't happy with just seven notes. Following the idea
above, we get a new octave for each of the four rows of the keyboard
above the space bar, with the top row having three additional notes,
like this:

[NOTE]
Notice each column of keyboard keys maps to the same note in different
octaves.

If you have used other notation software, you are probably used to look
for the `C` key if you want to write a _C_, and so on. This is not very
efficient, because sadly these letters aren’t ordered in such order in a
row. When writing notes with Cavatina, once you get your fingers placed
in the right position, you have all notes you need at your fingertips
and you don’t have to look back down at the keyboard.

=== Note length

So far we have 31 notes (covering a bit more than four octaves). Each of
these characters has its lowercase and uppercase variant, which
correspond to the note in 8^th^ and 4^th^ length accordingly. Switching
to the bold weight of Cavatina, you get 16^th^-notes in the lowercase
and 8^th^-notes in the uppercase characters.

[cols=",,",options="header",]
|=========================
| |Input |Note length
|Regular style |`a` |8^th^
|`A` |4^th^
|Bold style |`a` |16^th^
|`A` |8^th^
|=========================

[cols=",",options="header",]
|================================
|Input |Output
|`, a A a
                            A,` |
|================================

Appart from that, Cavatina has a special key that serves as a *modifier
key*: the `^`/`°` key. We are going to call `^` the inverter and `°` the
time character, the latter of which, among other things, extends the
duration of notes. Every time you hit the time key after a note, the
note’s length doubles. You can do this up to a maximum of twice per
note, i.e. for a whole note you would need to type a 4^th^-note followed
by two times `°`.

[cols=",",options="header",]
|=====================================
|Input |Output
|`, f F f~ f~~ F~ F~~,` |image:[image]
|=====================================

For dotted notes you use `<` after the note.

To draw a tie after a note append an `L`.

=== Note orientation

The stem of a note can be inverted. This is done with the inverter`^`. A
note can only be inverted once (which doesn’t stop you from
un-inverting).

To invert the stem of a chord you invert the first note of the chord. If
the next note in the chord would collide in its default orientation,
then it is automatically inverted. Otherwise keep inverting until you
obtain the desired result. This is useful for separating voices within
one chord.

[cols=",",options="header",]
|====================================================
|Input |Output
|`, f f^ j j^, afj a^fj a^f^j a^f^j^,` |image:[image]
|====================================================

=== Rests

Rests are accessed via the `ü`/`Ü` key. Their duration is changed the
same way as for notes. Optionally, you can write the same rest twice and
the length will increase accordingly.

[cols=",",options="header",]
|===========================================
|Input |Output
|`, ü Ü üü ÜÜ ü° ü°° Ü° Ü°°,` |image:[image]
|===========================================

=== Note beams

To beam two 8^th^ or 16^th^ notes, write two dots `..` after the second
note. Both notes need to have the same orientation before they can be
beamed. Currently only pairs of notes can be beamed.

[cols=",",options="header",]
|======================================================
|Input |Output
|`,  dh sj..  d^h^ s^..j  d^h s^..j^..,` |image:[image]
|======================================================

== Staff and Barlines

When you hit the spacebar you draw a new staff “block”. Before any note
or chord, you have to draw a new _staff_ block where this note or chord
will sit.

The barlines are located as follows:

[cols=",",options="header",]
|===========================
|Musical symbol |Raw input
|simple barline |`,`
|double barline |`,,`
|final barline |`.`
|repeat barline (start) |`;`
|repeat barline (end) |`:`
|===========================

Cavatina is not made to do minor adjustments to the layout, but if you
consider it necessary, you can gain control over horizontal spacing by
using the half space `-` and the quarter space `--`.

[cols=",",options="header",]
|===========================
|Input |Output
|`, ,, . ; :` |image:[image]
|===========================

== Clefs

Cavatina supports three different clefs:

[cols=",",options="header",]
|=========================
|Musical symbol |Raw input
|F-clef |`?`
|C-Clef |`?ß` or `ß?`
|G-Clef |`ß`
|=========================

The input of the notes is invariant of the signature; it doesn’t depend
on the current clef.

[cols=",",options="header",]
|=======================================
|Input |Output
|`,ß f f ,? f f,ß? f f ,` |image:[image]
|=======================================

== Time Signatures

Time signatures have to be written after clefs (and key signatures) or
barlines. To start a time signature enter the _time_ key `°`. After that
you just write the upper and lower numeral successively.

To write the _common time_ or _cut time_ symbols, enter `c` or `C` after
the _time_ key.

A space is automatically attached after a time signature, so that you
don’t have to open a new staff block yourself.

[cols=",",options="header",]
|===========================================
|Input |Output
|`,°34 ,°1216 ,?'''°34 ,°c ,` |image:[image]
|===========================================

== Articulations

[cols=",",options="header",]
|=========================
|Musical symbol |Raw input
|staccato |`ä`
|tenuto |`Ä`
|staccatissimo |`ää`
|fermata |`ÄÄ`
|accent |`>`
|=========================

All articulations are written after the lowest note of a chord, except
the fermata, which is written after the highest note.

[cols=",",options="header",]
|===================================
|Input |Output
|`  Aä AÄ Aää AÄÄ A>` |image:[image]
|===================================

== Dynamics

Dynamics are aligned with respect to the note to which they are applied.
Therefore, if you are writing a chord with some dynamics marking, you
should write that marking just after the first (lowest) note of the
chord.

.Note dynamics
[cols=",",options="header",]
|===============================================
|Musical symbol |Raw input
|pianississimo |`\*\*\*`
|pianissimo |`**`
|piano |`*`
|mezzo piano |`*+`
|mezzo forte |`+*`
|forte |`+`
|fortissimo |`++`
|fortississimo |`+++`
|sforzando |`++\*` or `\*\*+`
|forte-piano |`\*\*\*+` or `+++\*` or `**^` or `++^`
|===============================================

.Phrasal dynamics
[cols=",",options="header",]
|=========================
|Musical symbol |Raw input
|crescendo |`l`
|decrescendo |`l^`
|=========================

[cols=",",options="header",]
|==========================================
|Input |Output
|`  d*fh  h^++er  M**+  Dl ` |image:[image]
|==========================================

== Ornaments

[cols=",",options="header",]
|=========================
|Musical symbol |Raw input
|mordent |`ö`
|inv. mordent |`ö^`
|trill |`öö`
|turn |`Ö`
|inv. turn |`Ö^`
|arpeggio |`P`
|=========================

Note that, intuitively enough, ornaments are inverted with the
_inverter_ key `^`.

To extend the trill or the arpeggio repeat that same character. The
arpeggio is written at the end of a chord.

[cols=",",options="header",]
|==========================================
|Input |Output
|` Dö DÖ Dö^ DÖ^ Döö Döööö ` |image:[image]
|==========================================

== Repetition markings

Apart from the repeat barlines `;`/`:`, you can use the following
repetition markings:

[cols=",",options="header",]
|=========================
|Musical symbol |Raw input
|1^st^ repetition |`o`
|2^nd^ repetition |`oo`
|end marking |`o^`
|=========================

The end marking is necessary for the MusicXML/MIDI converter to detect
the range of the repetition sections.

[cols=",",options="header",]
|=========================
|Musical symbol |Raw input
|coda |`i`
|segno |`I`
|D.C. |k
|D.S. |K
|=========================

Writing _coda_ or _segno_ right after _D.C._ or _D.S._ will append the
words "al Coda" and "al Fine" accordingly.

[cols=",",options="header",]
|===================================================
|Input |Output
|`, D F G Do, D F D Go^:oo  D S A Ü.` |image:[image]
|===================================================

== Other Notation

Octave markings are used in a similar manner as repetition markings and
always after the highest note in a chord.

[cols=",",options="header",]
|=========================
|Musical symbol |Raw input
|8^va^ |`O`
|8^va^ (2) |`OO`
|end 8^va^ |`O^`
|=========================

The triplet is written before the chord sequence. Use tight spacing to
fit the notes under the mark: enter three quarter-spaces `---` between
the notes.

[cols=",",options="header",]
|=========================
|Musical symbol |Raw input
|triplet |`_`
|=========================

Pedal markings are lower markings and as such they have to be applied to
the first note of a chord.

[cols=",",options="header",]
|=========================
|Musical symbol |Raw input
|pedal |`p`
|release pedal |`pp`
|=========================

== Staff systems

To create systems of multiple staves you can extend barlines to join
with the upper staff. To draw a _grand staff_, first enter a newline
followed by a single barline `,` to start a new staff. To draw the brace
connecting with the upper staff, type in `**`. Then continue with the
clef and key signature as you would normally do. To connect the
subsequent barlines, write a single `*` after them.

[cols=",",options="header",]
|===============================
|Musical symbol |Raw input
|brace |`,**`
|long barlines |`,\*` or `.*` ...
|===============================

[cols=",",options="header",]
|==================================
|Input |Output
|`,ß''' DFJ DGJ J s d>..,
,**?''' A D Ü MJ ,*` |image:[image]
|==================================
